
step1: extract defs
DUPE METHOD: Method: DupeMethod.foo
DUPE: Class: Dupe (2)
 orig = dupe.php
 dupe = dupe.php
DUPE BAD STYLE: Class: DupeScript (3)
 orig = dupe_in_scripts.php
 dupe = scripts/s2.php
DUPE BAD STYLE: Function: __builtin__echo (2)
 orig = builtins.php
 dupe = scripts/redefine_regular_function.php

step2: extract inheritance
PB: lookup fail on Class: UndefinedExtendedClass (at class.php:45)

step3: extract uses
PB: lookup fail on ClassConstant: A.UNDEFINED_CLASS_CONSTANT (at class.php:32)
PB: lookup fail on Class: UndefinedClass (at class.php:50)
PB: lookup fail on Field: :x:misc.xnosuchstr= (at xhp_use.php:9)
PB: instanceof unknown class: Class: UNKNOWN_CLASS
