<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function oci_connect($username, $password, $db = null_string, $charset = null_string, $session_mode = k_OCI_DEFAULT) { }
function oci_new_connect($username, $password, $db = null_string, $charset = null_string, $session_mode = k_OCI_DEFAULT) { }
function oci_pconnect($username, $password, $db = null_string, $charset = null_string, $session_mode = k_OCI_DEFAULT) { }
function oci_server_version($connection) { }
function oci_password_change($connection, $username, $old_password, $new_password) { }
function oci_new_cursor($connection) { }
function oci_new_descriptor($connection, $type = k_OCI_DTYPE_LOB) { }
function oci_close($connection) { }
function oci_commit($connection) { }
function oci_rollback($connection) { }
function oci_error($source = null) { }
function oci_internal_debug($onoff) { }
function oci_parse($connection, $query) { }
function oci_statement_type($statement) { }
function oci_free_statement($statement) { }
function oci_free_descriptor($lob) { }
function oci_bind_array_by_name($statement, $name, &$var_array, $max_table_length, $max_item_length = -1, $type = k_SQLT_AFC) { }
function oci_bind_by_name($statement, $name, &$variable, $max_length = -1, $type = 0) { }
function oci_cancel($statement) { }
function oci_define_by_name($statement, $column_name, &$variable, $type = 0) { }
function oci_execute($statement, $mode = k_OCI_COMMIT_ON_SUCCESS) { }
function oci_num_fields($statement) { }
function oci_num_rows($statement) { }
function oci_result($statement, $field) { }
function oci_set_prefetch($statement, $rows) { }
function oci_fetch_all($statement, &$output, $skip = 0, $maxrows = -1, $flags = 0) { }
function oci_fetch_array($statement, $mode = null /* k_OCI_BOTH | k_OCI_RETURN_NULLS */) { }
function oci_fetch_assoc($statement) { }
function oci_fetch_object($statement, $mode = null /* k_OCI_ASSOC | k_OCI_RETURN_NULLS */) { }
function oci_fetch_row($statement) { }
function oci_fetch($statement) { }
function oci_field_is_null($statement, $field) { }
function oci_field_name($statement, $field) { }
function oci_field_precision($statement, $field) { }
function oci_field_scale($statement, $field) { }
function oci_field_size($statement, $field) { }
function oci_field_type_raw($statement, $field) { }
function oci_field_type($statement, $field) { }
