_server/htmlize_php2.cmo: htmlize_php2.ml
	$(ELIOMC) -c $(INCLUDES) -package tyxml htmlize_php2.mli
	$(ELIOMC) -c $(INCLUDES) -package tyxml $^


# _server/htmlize_php2.cmo \
# _server/lxr_server.cmo \

