<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function xml_parser_create() { }
function xml_parser_free() { }
function xml_parse() { }
function xml_parse_into_struct() { }
function xml_parser_create_ns() { }
function xml_parser_get_option() { }
function xml_parser_set_option() { }
function xml_set_character_data_handler() { }
function xml_set_default_handler() { }
function xml_set_element_handler() { }
function xml_set_processing_instruction_handler() { }
function xml_set_start_namespace_decl_handler() { }
function xml_set_end_namespace_decl_handler() { }
function xml_set_unparsed_entity_decl_handler() { }
function xml_set_external_entity_ref_handler() { }
function xml_set_notation_decl_handler() { }
function xml_set_object() { }
function xml_get_current_byte_index() { }
function xml_get_current_column_number() { }
function xml_get_current_line_number() { }
function xml_get_error_code() { }
function xml_error_string() { }
function utf8_decode() { }
function utf8_encode() { }
