<?php
/*
 * Purpose:    Cache a variable in the data store
 * Example:   
 *   <?php
 *   $bar = 'BAR';
 *   apc_add('foo', $bar);
 *   var_dump(apc_fetch('foo'));
 *   echo "\n";
 *   $bar = 'NEVER GETS SET';
 *   apc_add('foo', $bar);
 *   var_dump(apc_fetch('foo'));
 *   echo "\n";
 *   ?>
 * 
 * Output:   
 *   string(3) "BAR"
 *   string(3) "BAR"
 */
function apc_add(String $key, Variant $var, Int64 $ttl = 0, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose:    Cache a variable in the data store
 * Example:   
 *   <?php
 *   $bar = 'BAR';
 *   apc_store('foo', $bar);
 *   var_dump(apc_fetch('foo'));
 *   ?>
 * 
 * Output:   
 *   string(3) "BAR"
 */
function apc_store(String $key, Variant $var, Int64 $ttl = 0, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose:    Fetch a stored variable from the cache
 * Example:   
 *   <?php
 *   $bar = 'BAR';
 *   apc_store('foo', $bar);
 *   var_dump(apc_fetch('foo'));
 *   ?>
 * 
 * Output:   
 *   string(3) "BAR"
 */
function apc_fetch(Variant $key, Boolean &$success = null, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose:    Removes a stored variable from the cache
 * Example:   
 *   <?php
 *   $bar = 'BAR';
 *   apc_store('foo', $bar);
 *   apc_delete('foo');
 *   // this is obviously useless in this form
 *   ?>
 * 
 * Output: 
 */
function apc_delete(Variant $key, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose:    Stores a file in the bytecode cache, bypassing all filters.
 * Example: 
 * 
 * Output: 
 */
function apc_compile_file(String $filename, Boolean $atomic = true, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose:    Retrieves cached information from APC's data store
 * Example:   
 *   <?php
 *   print_r(apc_cache_info());
 *   ?>
 * 
 * Output:   
 *   Array
 *   (
 *       [num_slots] => 2000
 *       [ttl] => 0
 *       [num_hits] => 9
 *       [num_misses] => 3
 *       [start_time] => 1123958803
 *       [cache_list] => Array
 *           (
 *               [0] => Array
 *                   (
 *                       [filename] => /path/to/apc_test.php
 *                       [device] => 29954
 *                       [inode] => 1130511
 *                       [type] => file
 *                       [num_hits] => 1
 *                       [mtime] => 1123960686
 *                       [creation_time] => 1123960696
 *                       [deletion_time] => 0
 *                       [access_time] => 1123962864
 *                       [ref_count] => 1
 *                       [mem_size] => 677
 *                   )
 *               [1] => Array (...iterates for each cached file)
 *   )
 */
function apc_cache_info(Int64 $cache_id = 0, Boolean $limited = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose:    Clears the APC cache
 * Example: 
 * 
 * Output: 
 */
function apc_clear_cache(Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose:    Defines a set of constants for retrieval and mass-definition 
 * Example:   
 *   <?php
 *   $constants = array(
 *       'ONE'   => 1,
 *       'TWO'   => 2,
 *       'THREE' => 3,
 *   );
 *   apc_define_constants('numbers', $constants);
 *   echo ONE, TWO, THREE;
 *   ?>
 * 
 * Output:   
 *   123
 */
function apc_define_constants(String $key, String $constants, Boolean $case_sensitive = true, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose:    Loads a set of constants from the cache
 * Example:   
 *   <?php
 *   $constants = array(
 *       'ONE'   => 1,
 *       'TWO'   => 2,
 *       'THREE' => 3,
 *   );
 *   apc_define_constants('numbers', $constants);
 *   apc_load_constants('numbers');
 *   echo ONE, TWO, THREE;
 *   ?>
 * 
 * Output:   
 *   123
 */
function apc_load_constants(String $key, Boolean $case_sensitive = true, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose:    Retrieves APC's Shared Memory Allocation information
 * Example:   
 *   <?php
 *   print_r(apc_sma_info());
 *   ?>
 * 
 * Output:   
 *   Array
 *   (
 *       [num_seg] => 1
 *       [seg_size] => 31457280
 *       [avail_mem] => 31448408
 *       [block_lists] => Array
 *           (
 *               [0] => Array
 *                   (
 *                       [0] => Array
 *                           (
 *                               [size] => 31448408
 *                               [offset] => 8864
 *                           )
 *   
 *                   )
 *   
 *           )
 *   
 *   )
 */
function apc_sma_info(Boolean $limited = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function apc_filehits() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Deletes files from the opcode cache
 * Example:   
 *   <?php
 *   $filename = 'file.php';
 *   
 *   if (apc_compile_file($filename)) {
 *   
 *       if (apc_delete_file($filename)) {
 *           echo "Successfully deleted file $filename from APC cache.", PHP_EOL;
 *       }
 *   }
 *   
 *   if (apc_compile_file($filename)) {
 *   
 *       if ($good = apc_delete_file(array($filename, 'donotexist.php'))) {
 *           var_dump($good);
 *       }
 *   }
 *   
 *   $bad = apc_delete_file('donotexist.php');
 *   var_dump($bad);
 *   ?>
 * 
 * Output:   
 *   Successfully deleted file file.php from APC cache.
 *   [Mon May 24 09:30:33 2010] [apc-warning] Could not stat file donotexist.php, unable to delete from cache. in /tmp/test.php on line 13.
 *   array(1) {
 *     [0]=>
 *     string(14) "donotexist.php"
 *   }
 *   [Mon May 24 09:30:33 2010] [apc-warning] Could not stat file donotexist.php, unable to delete from cache. in /tmp/test.php on line 18.
 *   bool(false)
 */
function apc_delete_file(Variant $keys, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Increase a stored number
 * Example:   
 *   <?php
 *   echo "Let's do something with success", PHP_EOL;
 *   
 *   apc_store('anumber', 42);
 *   
 *   echo apc_fetch('anumber'), PHP_EOL;
 *   
 *   echo apc_inc('anumber'), PHP_EOL;
 *   echo apc_inc('anumber', 10), PHP_EOL;
 *   echo apc_inc('anumber', 10, $success), PHP_EOL;
 *   
 *   var_dump($success);
 *   
 *   echo "Now, let's fail", PHP_EOL, PHP_EOL;
 *   
 *   apc_store('astring', 'foo');
 *   
 *   $ret = apc_inc('astring', 1, $fail);
 *   
 *   var_dump($ret);
 *   var_dump($fail);
 *   ?>
 * 
 * Output:   
 *   42
 *   43
 *   53
 *   63
 *   bool(true)
 *   Now, let's fail
 *   
 *   bool(false)
 *   bool(false)
 */
function apc_inc(String $key, Int64 $step = 1, Boolean &$success = null, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Decrease a stored number
 * Example:   
 *   <?php
 *   echo "Let's do something with success", PHP_EOL;
 *   
 *   apc_store('anumber', 42);
 *   
 *   echo apc_fetch('anumber'), PHP_EOL;
 *   
 *   echo apc_dec('anumber'), PHP_EOL;
 *   echo apc_dec('anumber', 10), PHP_EOL;
 *   echo apc_dec('anumber', 10, $success), PHP_EOL;
 *   
 *   var_dump($success);
 *   
 *   echo "Now, let's fail", PHP_EOL, PHP_EOL;
 *   
 *   apc_store('astring', 'foo');
 *   
 *   $ret = apc_dec('astring', 1, $fail);
 *   
 *   var_dump($ret);
 *   var_dump($fail);
 *   ?>
 * 
 * Output:   
 *   Let's do something with success
 *   42
 *   41
 *   31
 *   21
 *   bool(true)
 *   
 *   Now, let's fail
 *   bool(false)
 *   bool(false)
 */
function apc_dec(String $key, Int64 $step = 1, Boolean &$success = null, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: apc_cas
 * Example:   
 *   <?php
 *   apc_store('foobar',2);
 *   echo '$foobar = 2', PHP_EOL;
 *   echo '$foobar == 1 ? 2 : 1 = ', (apc_cas('foobar', 1, 2) ? 'ok' : 'fail'), PHP_EOL;
 *   echo '$foobar == 2 ? 1 : 2 = ', (apc_cas('foobar', 2, 1) ? 'ok' : 'fail'), PHP_EOL;
 *   
 *   echo '$foobar = ', apc_fetch('foobar'), PHP_EOL;
 *   
 *   echo '$f__bar == 1 ? 2 : 1 = ', (apc_cas('f__bar', 1, 2) ? 'ok' : 'fail'), PHP_EOL;
 *   
 *   apc_store('perfection', 'xyz');
 *   echo '$perfection == 2 ? 1 : 2 = ', (apc_cas('perfection', 2, 1) ? 'ok' : 'epic fail'), PHP_EOL;
 *   
 *   echo '$foobar = ', apc_fetch('foobar'), PHP_EOL;
 *   ?>
 * 
 * Output:   
 *   $foobar = 2
 *   $foobar == 1 ? 2 : 1 = fail
 *   $foobar == 2 ? 1 : 2 = ok
 *   $foobar = 1
 *   $f__bar == 1 ? 2 : 1 = fail
 *   $perfection == 2 ? 1 : 2 = epic fail
 *   $foobar = 1
 */
function apc_cas(String $key, Int64 $old_cas, Int64 $new_cas, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get a binary dump of the given files and user variables
 * Example: 
 * 
 * Output: 
 */
function apc_bin_dump(Int64 $cache_id = 0, Variant $filter = null_variant) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Load a binary dump into the APC file/user cache
 * Example:   
 *   <?php
 *   $data = apc_bin_dump(NULL, NULL);
 *   apc_bin_load($data, APC_BIN_VERIFY_MD5 | APC_BIN_VERIFY_CRC32);
 *   ?>
 * 
 * Output: 
 */
function apc_bin_load(String $data, Int64 $flags = 0, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Output a binary dump of cached files and user variables to a file
 * Example: 
 * 
 * Output: 
 */
function apc_bin_dumpfile(Int64 $cache_id, Variant $filter, String $filename, Int64 $flags = 0, Resource $context = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Load a binary dump from a file into the APC file/user cache
 * Example: 
 * 
 * Output: 
 */
function apc_bin_loadfile(String $filename, Resource $context = null, Int64 $flags = 0, Int64 $cache_id = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

