<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function fb_set_opcode($opcode, $callback) { }
function fb_reset_opcode($opcode) { }
function fb_config_coredump($enabled, $limit) { }
function fb_debug_rlog($err, $include_flags = -1, $type = -1, $headers = null_variant) { }
function fb_backtrace($exception = null_variant) { }
function fb_render_wrapped($text, $linelen = 26, $head = "<span>", $tail = "</span><wbr></wbr><span class=\"word_break\"></span>") { }
function fb_add_included_file($filepath) { }
function fb_request_timers() { }
function fb_get_ape_version() { }
function fb_get_derived_classes($filename, $basecls) { }
function hotprofiler_enable($level) { }
function hotprofiler_disable() { }
function phprof_enable($flags = 0) { }
function phprof_disable() { }
function fql_set_static_data_10($tables, $functions) { }
function fql_static_data_set_10() { }
function fql_parse_10($query) { }
function fql_multiparse_10($query) { }
function xhp_preprocess_code($code) { }
function fb_call_user_func_array_async($function, $params) { }
function fb_call_user_func_async($function) { func_get_args();}
function fb_check_user_func_async($handle) { }
function fb_end_user_func_async($handle) { }
function fb_xbox_call_proxy($message) { }
