<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function session_set_cookie_params($lifetime, $path = null_string, $domain = null_string, $secure = null, $httponly = null) { }
function session_get_cookie_params() { }
function session_name($newname = null_string) { }
function session_module_name($newname = null_string) { }
function session_set_save_handler($open, $close, $read, $write, $destroy, $gc) { }
function session_save_path($newname = null_string) { }
function session_id($newid = null_string) { }
function session_regenerate_id($delete_old_session = false) { }
function session_cache_limiter($new_cache_limiter = null_string) { }
function session_cache_expire($new_cache_expire = null_string) { }
function session_encode() { }
function session_decode($data) { }
function session_start() { }
function session_destroy() { }
function session_unset() { }
function session_commit() { }
function session_write_close() { }
function session_register($var_names) { func_get_args();}
function session_unregister($varname) { }
function session_is_registered($varname) { }
