<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function use_soap_error_handler($handler = true) { }
function is_soap_fault($fault) { }
function _soap_active_version() { }
class SoapServer {
 function __construct($wsdl, $options = null_array) { }
 function setclass($name) { func_get_args();}
 function setobject($obj) { }
 function addfunction($func) { }
 function getfunctions() { }
 function handle($request = null_string) { }
 function setpersistence($mode) { }
 function fault($code, $fault, $actor = null_string, $detail = null, $name = null_string) { }
 function addsoapheader($fault) { }
 function __destruct() { }
}
class SoapClient {
 function __construct($wsdl, $options = null_array) { }
 function __call($name, $args) { }
 function __soapcall($name, $args, $options = null_array, $input_headers = null_variant, &$output_headers = null) { }
 function __getlastrequest() { }
 function __getlastresponse() { }
 function __getlastrequestheaders() { }
 function __getlastresponseheaders() { }
 function __getfunctions() { }
 function __gettypes() { }
 function __dorequest($buf, $location, $action, $version, $oneway = false) { }
 function __setcookie($name, $value = null_string) { }
 function __setlocation($new_location = null_string) { }
 function __setsoapheaders($headers = null_variant) { }
 function __destruct() { }
}
class SoapVar {
 function __construct($data, $type, $type_name = null_string, $type_namespace = null_string, $node_name = null_string, $node_namespace = null_string) { }
 function __destruct() { }
}
class SoapFault {
 function __construct($code, $message, $actor = null_string, $detail = null, $name = null_string, $header = null) { }
 function __tostring() { }
 function __destruct() { }
}
class SoapParam {
 function __construct($data, $name) { }
 function __destruct() { }
}
class SoapHeader {
 function __construct($ns, $name, $data = null, $mustunderstand = false, $actor = null) { }
 function __destruct() { }
}
