<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function hphpd_install_user_command($cmd, $clsname) { }
function hphpd_get_user_commands() { }
function hphpd_break($condition = true) { }
class DebuggerProxy {
 function __construct() { }
 function isLocal() { }
 function send($cmd) { }
 function __destruct() { }
}
class DebuggerClient {
const AUTO_COMPLETE_FILENAMES = 0;
const AUTO_COMPLETE_VARIABLES = 0;
const AUTO_COMPLETE_CONSTANTS = 0;
const AUTO_COMPLETE_CLASSES = 0;
const AUTO_COMPLETE_FUNCTIONS = 0;
const AUTO_COMPLETE_CLASS_METHODS = 0;
const AUTO_COMPLETE_CLASS_PROPERTIES = 0;
const AUTO_COMPLETE_CLASS_CONSTANTS = 0;
const AUTO_COMPLETE_KEYWORDS = 0;
const AUTO_COMPLETE_CODE = 0;
 function __construct() { }
 function quit() { }
 function help($format) { }
 function info($format) { }
 function output($format) { }
 function error($format) { }
 function code($source, $highlight_line = 0, $start_line_no = 0, $end_line_no = 0) { }
 function ask($format) { }
 function wrap($str) { }
 function helpTitle($str) { }
 function helpCmds($cmd, $desc) { }
 function helpBody($str) { }
 function helpSection($str) { }
 function tutorial($str) { }
 function getCode() { }
 function getCommand() { }
 function arg($index, $str) { }
 function argCount() { }
 function argValue($index) { }
 function argRest($index) { }
 function args() { }
 function send($cmd) { }
 function xend($cmd) { }
 function getCurrentLocation() { }
 function getStackTrace() { }
 function getFrame() { }
 function printFrame($index) { }
 function addCompletion($list) { }
 function __destruct() { }
}
