<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function mail() { }
function ezmlm_hash() { }
function mailparse_msg_create() { }
function mailparse_msg_free() { }
function mailparse_msg_parse_file() { }
function mailparse_msg_parse() { }
function mailparse_msg_extract_part_file() { }
function mailparse_msg_extract_whole_part_file() { }
function mailparse_msg_extract_part() { }
function mailparse_msg_get_part_data() { }
function mailparse_msg_get_part() { }
function mailparse_msg_get_structure() { }
function mailparse_rfc822_parse_addresses() { }
function mailparse_stream_encode() { }
function mailparse_uudecode_all() { }
function mailparse_determine_best_xfer_encoding() { }
