<?php
function dangling_server_proxy_old_request() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function dangling_server_proxy_new_request(String $host) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

