<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function is_bool($var) { }
function is_int($var) { }
function is_integer($var) { }
function is_long($var) { }
function is_double($var) { }
function is_float($var) { }
function is_numeric($var) { }
function is_real($var) { }
function is_string($var) { }
function is_scalar($var) { }
function is_array($var) { }
function is_object($var) { }
function is_resource($var) { }
function is_null($var) { }
function gettype($v) { }
function get_resource_type($handle) { }
function intval($v, $base = 10) { }
function doubleval($v) { }
function floatval($v) { }
function strval($v) { }
function settype(&$var, $type) { }
function print_r($expression, $ret = false) { }
function var_export($expression, $ret = false) { }
function var_dump($expression) { func_get_args();}
function debug_zval_dump($variable) { }
function serialize($value) { }
function unserialize($str) { }
function get_defined_vars() { }
function import_request_variables($types, $prefix = "") { }
function extract($var_array, $extract_type = k_EXTR_OVERWRITE, $prefix = "") { }
