<?php
function MagickGetCopyright() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetHomeURL() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetPackageName() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetQuantumDepth() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetReleaseDate() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetResourceLimit(Int32 $resource_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetVersion() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetVersionNumber() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetVersionString() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickQueryConfigureOption(String $option) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickQueryConfigureOptions(String $pattern) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickQueryFonts(String $pattern) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickQueryFormats(String $pattern) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetResourceLimit(Int32 $resource_type, Double $limit) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function NewDrawingWand() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function NewMagickWand() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function NewPixelIterator(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function NewPixelRegionIterator(Resource $mgck_wnd, Int32 $x, Int32 $y, Int32 $columns, Int32 $rows) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function NewPixelWand(String $imagemagick_col_str = null_string) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function NewPixelWandArray(Int32 $num_pxl_wnds) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function NewPixelWands(Int32 $num_pxl_wnds) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DestroyDrawingWand(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DestroyMagickWand(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DestroyPixelIterator(Resource $pxl_iter) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DestroyPixelWand(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DestroyPixelWandArray(VariantVec $pxl_wnd_array) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DestroyPixelWands(VariantVec $pxl_wnd_array) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function IsDrawingWand(Variant $var) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function IsMagickWand(Variant $var) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function IsPixelIterator(Variant $var) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function IsPixelWand(Variant $var) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function ClearDrawingWand(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function ClearMagickWand(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function ClearPixelIterator(Resource $pxl_iter) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function ClearPixelWand(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function CloneDrawingWand(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function CloneMagickWand(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function WandGetException(Resource $wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function WandGetExceptionString(Resource $wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function WandGetExceptionType(Resource $wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function WandHasException(Resource $wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawAffine(Resource $drw_wnd, Double $sx, Double $sy, Double $rx, Double $ry, Double $tx, Double $ty) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawAnnotation(Resource $drw_wnd, Double $x, Double $y, String $text) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawArc(Resource $drw_wnd, Double $sx, Double $sy, Double $ex, Double $ey, Double $sd, Double $ed) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawBezier(Resource $drw_wnd, VariantVec $x_y_points_array) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawCircle(Resource $drw_wnd, Double $ox, Double $oy, Double $px, Double $py) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawColor(Resource $drw_wnd, Double $x, Double $y, Int32 $paint_method) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawComment(Resource $drw_wnd, String $comment) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawComposite(Resource $drw_wnd, Int32 $composite_operator, Double $x, Double $y, Double $width, Double $height, Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawEllipse(Resource $drw_wnd, Double $ox, Double $oy, Double $rx, Double $ry, Double $start, Double $end) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetClipPath(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetClipRule(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetClipUnits(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetException(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetExceptionString(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetExceptionType(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetFillAlpha(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetFillColor(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetFillOpacity(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetFillRule(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetFont(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetFontFamily(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetFontSize(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetFontStretch(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetFontStyle(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetFontWeight(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetGravity(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetStrokeAlpha(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetStrokeAntialias(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetStrokeColor(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetStrokeDashArray(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetStrokeDashOffset(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetStrokeLineCap(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetStrokeLineJoin(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetStrokeMiterLimit(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetStrokeOpacity(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetStrokeWidth(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetTextAlignment(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetTextAntialias(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetTextDecoration(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetTextEncoding(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetTextUnderColor(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawGetVectorGraphics(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawLine(Resource $drw_wnd, Double $sx, Double $sy, Double $ex, Double $ey) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawMatte(Resource $drw_wnd, Double $x, Double $y, Int32 $paint_method) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathClose(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathCurveToAbsolute(Resource $drw_wnd, Double $x1, Double $y1, Double $x2, Double $y2, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathCurveToQuadraticBezierAbsolute(Resource $drw_wnd, Double $x1, Double $y1, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathCurveToQuadraticBezierRelative(Resource $drw_wnd, Double $x1, Double $y1, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathCurveToQuadraticBezierSmoothAbsolute(Resource $drw_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathCurveToQuadraticBezierSmoothRelative(Resource $drw_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathCurveToRelative(Resource $drw_wnd, Double $x1, Double $y1, Double $x2, Double $y2, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathCurveToSmoothAbsolute(Resource $drw_wnd, Double $x2, Double $y2, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathCurveToSmoothRelative(Resource $drw_wnd, Double $x2, Double $y2, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathEllipticArcAbsolute(Resource $drw_wnd, Double $rx, Double $ry, Double $x_axis_rotation, Boolean $large_arc_flag, Boolean $sweep_flag, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathEllipticArcRelative(Resource $drw_wnd, Double $rx, Double $ry, Double $x_axis_rotation, Boolean $large_arc_flag, Boolean $sweep_flag, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathFinish(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathLineToAbsolute(Resource $drw_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathLineToHorizontalAbsolute(Resource $drw_wnd, Double $x) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathLineToHorizontalRelative(Resource $drw_wnd, Double $x) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathLineToRelative(Resource $drw_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathLineToVerticalAbsolute(Resource $drw_wnd, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathLineToVerticalRelative(Resource $drw_wnd, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathMoveToAbsolute(Resource $drw_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathMoveToRelative(Resource $drw_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPathStart(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPoint(Resource $drw_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPolygon(Resource $drw_wnd, VariantVec $x_y_points_array) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPolyline(Resource $drw_wnd, VariantVec $x_y_points_array) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawRectangle(Resource $drw_wnd, Double $x1, Double $y1, Double $x2, Double $y2) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawRender(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawRotate(Resource $drw_wnd, Double $degrees) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawRoundRectangle(Resource $drw_wnd, Double $x1, Double $y1, Double $x2, Double $y2, Double $rx, Double $ry) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawScale(Resource $drw_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetClipPath(Resource $drw_wnd, String $clip_path) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetClipRule(Resource $drw_wnd, Int32 $fill_rule) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetClipUnits(Resource $drw_wnd, Int32 $clip_path_units) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetFillAlpha(Resource $drw_wnd, Double $fill_opacity) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetFillColor(Resource $drw_wnd, Resource $fill_pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetFillOpacity(Resource $drw_wnd, Double $fill_opacity) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetFillPatternURL(Resource $drw_wnd, String $fill_url) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetFillRule(Resource $drw_wnd, Int32 $fill_rule) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetFont(Resource $drw_wnd, String $font_file) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetFontFamily(Resource $drw_wnd, String $font_family) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetFontSize(Resource $drw_wnd, Double $pointsize) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetFontStretch(Resource $drw_wnd, Int32 $stretch_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetFontStyle(Resource $drw_wnd, Int32 $style_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetFontWeight(Resource $drw_wnd, Double $font_weight) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetGravity(Resource $drw_wnd, Int32 $gravity_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetStrokeAlpha(Resource $drw_wnd, Double $stroke_opacity) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetStrokeAntialias(Resource $drw_wnd, Boolean $stroke_antialias = true) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetStrokeColor(Resource $drw_wnd, Resource $strokecolor_pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetStrokeDashArray(Resource $drw_wnd, VariantVec $dash_array = null_array) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetStrokeDashOffset(Resource $drw_wnd, Double $dash_offset) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetStrokeLineCap(Resource $drw_wnd, Int32 $line_cap) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetStrokeLineJoin(Resource $drw_wnd, Int32 $line_join) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetStrokeMiterLimit(Resource $drw_wnd, Double $miterlimit) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetStrokeOpacity(Resource $drw_wnd, Double $stroke_opacity) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetStrokePatternURL(Resource $drw_wnd, String $stroke_url) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetStrokeWidth(Resource $drw_wnd, Double $stroke_width) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetTextAlignment(Resource $drw_wnd, Int32 $align_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetTextAntialias(Resource $drw_wnd, Boolean $text_antialias = true) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetTextDecoration(Resource $drw_wnd, Int32 $decoration_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetTextEncoding(Resource $drw_wnd, String $encoding) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetTextUnderColor(Resource $drw_wnd, Resource $undercolor_pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetVectorGraphics(Resource $drw_wnd, String $vector_graphics) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSetViewbox(Resource $drw_wnd, Double $x1, Double $y1, Double $x2, Double $y2) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSkewX(Resource $drw_wnd, Double $degrees) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawSkewY(Resource $drw_wnd, Double $degrees) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawTranslate(Resource $drw_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PushDrawingWand(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPushClipPath(Resource $drw_wnd, String $clip_path_id) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPushDefs(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPushPattern(Resource $drw_wnd, String $pattern_id, Double $x, Double $y, Double $width, Double $height) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PopDrawingWand(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPopClipPath(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPopDefs(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function DrawPopPattern(Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickAdaptiveThresholdImage(Resource $mgck_wnd, Double $width, Double $height, Double $offset) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickAddImage(Resource $mgck_wnd, Resource $add_wand) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickAddNoiseImage(Resource $mgck_wnd, Int32 $noise_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickAffineTransformImage(Resource $mgck_wnd, Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickAnnotateImage(Resource $mgck_wnd, Resource $drw_wnd, Double $x, Double $y, Double $angle, String $text) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickAppendImages(Resource $mgck_wnd, Boolean $stack_vertical = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickAverageImages(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickBlackThresholdImage(Resource $mgck_wnd, Resource $threshold_pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickBlurImage(Resource $mgck_wnd, Double $radius, Double $sigma, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickBorderImage(Resource $mgck_wnd, Resource $bordercolor, Double $width, Double $height) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickCharcoalImage(Resource $mgck_wnd, Double $radius, Double $sigma) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickChopImage(Resource $mgck_wnd, Double $width, Double $height, Int32 $x, Int32 $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickClipImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickClipPathImage(Resource $mgck_wnd, String $pathname, Boolean $inside) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickCoalesceImages(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickColorFloodfillImage(Resource $mgck_wnd, Resource $fillcolor_pxl_wnd, Double $fuzz, Resource $bordercolor_pxl_wnd, Int32 $x, Int32 $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickColorizeImage(Resource $mgck_wnd, Resource $colorize, Resource $opacity_pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickCombineImages(Resource $mgck_wnd, Int32 $channel_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickCommentImage(Resource $mgck_wnd, String $comment) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickCompareImages(Resource $mgck_wnd, Resource $reference_wnd, Int32 $metric_type, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickCompositeImage(Resource $mgck_wnd, Resource $composite_wnd, Int32 $composite_operator, Int32 $x, Int32 $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickConstituteImage(Resource $mgck_wnd, Double $columns, Double $rows, String $smap, Int32 $storage_type, VariantVec $pixel_array) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickContrastImage(Resource $mgck_wnd, Boolean $sharpen) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickConvolveImage(Resource $mgck_wnd, VariantVec $kernel_array, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickCropImage(Resource $mgck_wnd, Double $width, Double $height, Int32 $x, Int32 $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickCycleColormapImage(Resource $mgck_wnd, Int32 $num_positions) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickDeconstructImages(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickDescribeImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickDespeckleImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickDrawImage(Resource $mgck_wnd, Resource $drw_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickEchoImageBlob(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickEchoImagesBlob(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickEdgeImage(Resource $mgck_wnd, Double $radius) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickEmbossImage(Resource $mgck_wnd, Double $radius, Double $sigma) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickEnhanceImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickEqualizeImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickEvaluateImage(Resource $mgck_wnd, Int32 $evaluate_op, Double $constant, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickFlattenImages(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickFlipImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickFlopImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickFrameImage(Resource $mgck_wnd, Resource $matte_color, Double $width, Double $height, Int32 $inner_bevel, Int32 $outer_bevel) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickFxImage(Resource $mgck_wnd, String $expression, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGammaImage(Resource $mgck_wnd, Double $gamma, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGaussianBlurImage(Resource $mgck_wnd, Double $radius, Double $sigma, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetCharHeight(Resource $mgck_wnd, Resource $drw_wnd, String $txt, Boolean $multiline = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetCharWidth(Resource $mgck_wnd, Resource $drw_wnd, String $txt, Boolean $multiline = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetException(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetExceptionString(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetExceptionType(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetFilename(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetFormat(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageBackgroundColor(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageBlob(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageBluePrimary(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageBorderColor(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageChannelMean(Resource $mgck_wnd, Int32 $channel_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageColormapColor(Resource $mgck_wnd, Double $index) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageColors(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageColorspace(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageCompose(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageCompression(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageCompressionQuality(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageDelay(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageDepth(Resource $mgck_wnd, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageDispose(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageExtrema(Resource $mgck_wnd, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageFilename(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageFormat(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageGamma(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageGreenPrimary(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageHeight(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageHistogram(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageIndex(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageInterlaceScheme(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageIterations(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageMatteColor(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageMimeType(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImagePixels(Resource $mgck_wnd, Int32 $x_offset, Int32 $y_offset, Double $columns, Double $rows, String $smap, Int32 $storage_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageProfile(Resource $mgck_wnd, String $name) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageRedPrimary(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageRenderingIntent(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageResolution(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageScene(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageSignature(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageSize(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageType(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageUnits(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageVirtualPixelMethod(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageWhitePoint(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImageWidth(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetImagesBlob(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetInterlaceScheme(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetMaxTextAdvance(Resource $mgck_wnd, Resource $drw_wnd, String $txt, Boolean $multiline = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetMimeType(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetNumberImages(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetSamplingFactors(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetSize(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetStringHeight(Resource $mgck_wnd, Resource $drw_wnd, String $txt, Boolean $multiline = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetStringWidth(Resource $mgck_wnd, Resource $drw_wnd, String $txt, Boolean $multiline = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetTextAscent(Resource $mgck_wnd, Resource $drw_wnd, String $txt, Boolean $multiline = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetTextDescent(Resource $mgck_wnd, Resource $drw_wnd, String $txt, Boolean $multiline = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickGetWandSize(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickHasNextImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickHasPreviousImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickImplodeImage(Resource $mgck_wnd, Double $amount) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickLabelImage(Resource $mgck_wnd, String $label) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickLevelImage(Resource $mgck_wnd, Double $black_point, Double $gamma, Double $white_point, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickMagnifyImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickMapImage(Resource $mgck_wnd, Resource $map_wand, Boolean $dither) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickMatteFloodfillImage(Resource $mgck_wnd, Double $opacity, Double $fuzz, Resource $bordercolor_pxl_wnd, Int32 $x, Int32 $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickMedianFilterImage(Resource $mgck_wnd, Double $radius) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickMinifyImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickModulateImage(Resource $mgck_wnd, Double $brightness, Double $saturation, Double $hue) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickMontageImage(Resource $mgck_wnd, Resource $drw_wnd, String $tile_geometry, String $thumbnail_geometry, Int32 $montage_mode, String $frame) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickMorphImages(Resource $mgck_wnd, Double $number_frames) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickMosaicImages(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickMotionBlurImage(Resource $mgck_wnd, Double $radius, Double $sigma, Double $angle) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickNegateImage(Resource $mgck_wnd, Boolean $only_the_gray = false, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickNewImage(Resource $mgck_wnd, Double $width, Double $height, String $imagemagick_col_str = null_string) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickNextImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickNormalizeImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickOilPaintImage(Resource $mgck_wnd, Double $radius) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickPaintOpaqueImage(Resource $mgck_wnd, Resource $target_pxl_wnd, Resource $fill_pxl_wnd, Double $fuzz = 0.0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickPaintTransparentImage(Resource $mgck_wnd, Resource $target, Double $opacity = k_MW_TransparentOpacity, Double $fuzz = 0.0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickPingImage(Resource $mgck_wnd, String $filename) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickPosterizeImage(Resource $mgck_wnd, Double $levels, Boolean $dither) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickPreviewImages(Resource $mgck_wnd, Int32 $preview) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickPreviousImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickProfileImage(Resource $mgck_wnd, String $name, String $profile = null_string) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickQuantizeImage(Resource $mgck_wnd, Double $number_colors, Int32 $colorspace_type, Double $treedepth, Boolean $dither, Boolean $measure_error) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickQuantizeImages(Resource $mgck_wnd, Double $number_colors, Int32 $colorspace_type, Double $treedepth, Boolean $dither, Boolean $measure_error) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickQueryFontMetrics(Resource $mgck_wnd, Resource $drw_wnd, String $txt, Boolean $multiline = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickRadialBlurImage(Resource $mgck_wnd, Double $angle) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickRaiseImage(Resource $mgck_wnd, Double $width, Double $height, Int32 $x, Int32 $y, Boolean $raise) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickReadImage(Resource $mgck_wnd, String $filename) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickReadImageBlob(Resource $mgck_wnd, String $blob) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickReadImageFile(Resource $mgck_wnd, Resource $handle) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickReadImages(Resource $mgck_wnd, StringVec $img_filenames_array) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickReduceNoiseImage(Resource $mgck_wnd, Double $radius) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickRemoveImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickRemoveImageProfile(Resource $mgck_wnd, String $name) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickRemoveImageProfiles(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickResampleImage(Resource $mgck_wnd, Double $x_resolution, Double $y_resolution, Int32 $filter_type, Double $blur) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickResetIterator(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickResizeImage(Resource $mgck_wnd, Double $columns, Double $rows, Int32 $filter_type, Double $blur) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickRollImage(Resource $mgck_wnd, Int32 $x_offset, Int32 $y_offset) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickRotateImage(Resource $mgck_wnd, Resource $background, Double $degrees) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSampleImage(Resource $mgck_wnd, Double $columns, Double $rows) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickScaleImage(Resource $mgck_wnd, Double $columns, Double $rows) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSeparateImageChannel(Resource $mgck_wnd, Int32 $channel_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetCompressionQuality(Resource $mgck_wnd, Double $quality) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetFilename(Resource $mgck_wnd, String $filename = null_string) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetFirstIterator(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetFormat(Resource $mgck_wnd, String $format) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImage(Resource $mgck_wnd, Resource $replace_wand) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageBackgroundColor(Resource $mgck_wnd, Resource $background_pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageBias(Resource $mgck_wnd, Double $bias) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageBluePrimary(Resource $mgck_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageBorderColor(Resource $mgck_wnd, Resource $border_pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageColormapColor(Resource $mgck_wnd, Double $index, Resource $mapcolor_pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageColorspace(Resource $mgck_wnd, Int32 $colorspace_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageCompose(Resource $mgck_wnd, Int32 $composite_operator) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageCompression(Resource $mgck_wnd, Int32 $compression_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageCompressionQuality(Resource $mgck_wnd, Double $quality) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageDelay(Resource $mgck_wnd, Double $delay) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageDepth(Resource $mgck_wnd, Int32 $depth, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageDispose(Resource $mgck_wnd, Int32 $dispose_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageFilename(Resource $mgck_wnd, String $filename = null_string) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageFormat(Resource $mgck_wnd, String $format) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageGamma(Resource $mgck_wnd, Double $gamma) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageGreenPrimary(Resource $mgck_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageIndex(Resource $mgck_wnd, Int32 $index) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageInterlaceScheme(Resource $mgck_wnd, Int32 $interlace_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageIterations(Resource $mgck_wnd, Double $iterations) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageMatteColor(Resource $mgck_wnd, Resource $matte_pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageOption(Resource $mgck_wnd, String $format, String $key, String $value) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImagePixels(Resource $mgck_wnd, Int32 $x_offset, Int32 $y_offset, Double $columns, Double $rows, String $smap, Int32 $storage_type, VariantVec $pixel_array) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageProfile(Resource $mgck_wnd, String $name, String $profile) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageRedPrimary(Resource $mgck_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageRenderingIntent(Resource $mgck_wnd, Int32 $rendering_intent) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageResolution(Resource $mgck_wnd, Double $x_resolution, Double $y_resolution) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageScene(Resource $mgck_wnd, Double $scene) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageType(Resource $mgck_wnd, Int32 $image_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageUnits(Resource $mgck_wnd, Int32 $resolution_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageVirtualPixelMethod(Resource $mgck_wnd, Int32 $virtual_pixel_method) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetImageWhitePoint(Resource $mgck_wnd, Double $x, Double $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetInterlaceScheme(Resource $mgck_wnd, Int32 $interlace_type) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetLastIterator(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetPassphrase(Resource $mgck_wnd, String $passphrase) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetResolution(Resource $mgck_wnd, Double $x_resolution, Double $y_resolution) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetSamplingFactors(Resource $mgck_wnd, Double $number_factors, VariantVec $sampling_factors) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetSize(Resource $mgck_wnd, Int32 $columns, Int32 $rows) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSetWandSize(Resource $mgck_wnd, Int32 $columns, Int32 $rows) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSharpenImage(Resource $mgck_wnd, Double $radius, Double $sigma, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickShaveImage(Resource $mgck_wnd, Int32 $columns, Int32 $rows) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickShearImage(Resource $mgck_wnd, Resource $background, Double $x_shear, Double $y_shear) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSolarizeImage(Resource $mgck_wnd, Double $threshold) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSpliceImage(Resource $mgck_wnd, Double $width, Double $height, Int32 $x, Int32 $y) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSpreadImage(Resource $mgck_wnd, Double $radius) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSteganoImage(Resource $mgck_wnd, Resource $watermark_wand, Int32 $offset) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickStereoImage(Resource $mgck_wnd, Resource $offset_wand) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickStripImage(Resource $mgck_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickSwirlImage(Resource $mgck_wnd, Double $degrees) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickTextureImage(Resource $mgck_wnd, Resource $texture_wand) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickThresholdImage(Resource $mgck_wnd, Double $threshold, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickTintImage(Resource $mgck_wnd, Int32 $tint_pxl_wnd, Resource $opacity_pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickTransformImage(Resource $mgck_wnd, String $crop, String $geometry) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickTrimImage(Resource $mgck_wnd, Double $fuzz) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickUnsharpMaskImage(Resource $mgck_wnd, Double $radius, Double $sigma, Double $amount, Double $threshold, Int32 $channel_type = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickWaveImage(Resource $mgck_wnd, Double $amplitude, Double $wave_length) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickWhiteThresholdImage(Resource $mgck_wnd, Resource $threshold_pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickWriteImage(Resource $mgck_wnd, String $filename) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickWriteImageFile(Resource $mgck_wnd, Resource $handle) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickWriteImages(Resource $mgck_wnd, String $filename = "", Boolean $join_images = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function MagickWriteImagesFile(Resource $mgck_wnd, Resource $handle) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetAlpha(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetAlphaQuantum(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetBlack(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetBlackQuantum(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetBlue(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetBlueQuantum(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetColorAsString(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetColorCount(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetCyan(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetCyanQuantum(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetException(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetExceptionString(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetExceptionType(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetGreen(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetGreenQuantum(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetIndex(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetMagenta(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetMagentaQuantum(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetOpacity(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetOpacityQuantum(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetQuantumColor(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetRed(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetRedQuantum(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetYellow(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetYellowQuantum(Resource $pxl_wnd) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetAlpha(Resource $pxl_wnd, Double $alpha) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetAlphaQuantum(Resource $pxl_wnd, Double $alpha) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetBlack(Resource $pxl_wnd, Double $black) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetBlackQuantum(Resource $pxl_wnd, Double $black) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetBlue(Resource $pxl_wnd, Double $blue) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetBlueQuantum(Resource $pxl_wnd, Double $blue) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetColor(Resource $pxl_wnd, String $imagemagick_col_str) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetColorCount(Resource $pxl_wnd, Int32 $count) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetCyan(Resource $pxl_wnd, Double $cyan) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetCyanQuantum(Resource $pxl_wnd, Double $cyan) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetGreen(Resource $pxl_wnd, Double $green) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetGreenQuantum(Resource $pxl_wnd, Double $green) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetIndex(Resource $pxl_wnd, Double $index) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetMagenta(Resource $pxl_wnd, Double $magenta) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetMagentaQuantum(Resource $pxl_wnd, Double $magenta) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetOpacity(Resource $pxl_wnd, Double $opacity) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetOpacityQuantum(Resource $pxl_wnd, Double $opacity) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetQuantumColor(Resource $pxl_wnd, Double $red, Double $green, Double $blue, Double $opacity = 0.0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetRed(Resource $pxl_wnd, Double $red) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetRedQuantum(Resource $pxl_wnd, Double $red) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetYellow(Resource $pxl_wnd, Double $yellow) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetYellowQuantum(Resource $pxl_wnd, Double $yellow) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetIteratorException(Resource $pxl_iter) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetIteratorExceptionString(Resource $pxl_iter) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetIteratorExceptionType(Resource $pxl_iter) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelGetNextIteratorRow(Resource $pxl_iter) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelResetIterator(Resource $pxl_iter) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSetIteratorRow(Resource $pxl_iter, Int32 $row) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function PixelSyncIterator(Resource $pxl_iter) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

