<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function get_declared_classes() { }
function get_declared_interfaces() { }
function class_exists() { }
function interface_exists() { }
function get_class_methods() { }
function get_class_vars() { }
function get_class() { }
function get_parent_class() { }
function is_a() { }
function is_subclass_of() { }
function method_exists() { }
function property_exists() { }
function get_object_vars() { }
function call_user_method_array() { }
function call_user_method() { }
