<?php
/*
 * Purpose: Returns the JSON representation of a value
 * Example:   
 *   <?php
 *   $arr = array ('a'=>1,'b'=>2,'c'=>3,'d'=>4,'e'=>5);
 *   
 *   echo json_encode($arr);
 *   ?>
 * 
 * Output:   
 *   {"a":1,"b":2,"c":3,"d":4,"e":5}
 */
function json_encode(Variant $value, Boolean $loose = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Decodes a JSON string
 * Example:   
 *   <?php
 *   $json = '{"a":1,"b":2,"c":3,"d":4,"e":5}';
 *   
 *   var_dump(json_decode($json));
 *   var_dump(json_decode($json, true));
 *   
 *   ?>
 * 
 * Output:   
 *   object(stdClass)#1 (5) {
 *       ["a"] => int(1)
 *       ["b"] => int(2)
 *       ["c"] => int(3)
 *       ["d"] => int(4)
 *       ["e"] => int(5)
 *   }
 *   
 *   array(5) {
 *       ["a"] => int(1)
 *       ["b"] => int(2)
 *       ["c"] => int(3)
 *       ["d"] => int(4)
 *       ["e"] => int(5)
 *   }
 */
function json_decode(String $json, Boolean $assoc = false, Boolean $loose = false) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

