<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function ftok() { }
function msg_get_queue() { }
function msg_send() { }
function msg_receive() { }
function msg_remove_queue() { }
function msg_set_queue() { }
function msg_stat_queue() { }
function sem_acquire() { }
function sem_get() { }
function sem_release() { }
function sem_remove() { }
function shm_attach() { }
function shm_detach() { }
function shm_remove() { }
function shm_get_var() { }
function shm_put_var() { }
function shm_remove_var() { }
