<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function bcscale($scale) { }
function bcadd($left, $right, $scale = -1) { }
function bcsub($left, $right, $scale = -1) { }
function bccomp($left, $right, $scale = -1) { }
function bcmul($left, $right, $scale = -1) { }
function bcdiv($left, $right, $scale = -1) { }
function bcmod($left, $right) { }
function bcpow($left, $right, $scale = -1) { }
function bcpowmod($left, $right, $modulus, $scale = -1) { }
function bcsqrt($operand, $scale = -1) { }
