<?hh     /* -*- php -*- */
// THIS IS AUTOGENERATED BY builtins_php.ml

function session_set_cookie_params($lifetime, $path = null, $domain = null, $secure = null, $httponly = null) { }
function session_get_cookie_params() { }
function session_name($newname = null) { }
function session_module_name($newname = null) { }
function hphp_session_set_save_handler($sessionhandler, $register_shutdown = true) { }
function session_save_path($newname = null) { }
function session_id($newid = null) { }
function session_regenerate_id($delete_old_session = false) { }
function session_cache_limiter($new_cache_limiter = null) { }
function session_cache_expire($new_cache_expire = null) { }
function session_encode() { }
function session_decode($data) { }
function session_start() { }
function session_destroy() { }
function session_unset() { }
function session_commit() { }
function session_write_close() { }
function session_register($var_names, ...) { }
function session_unregister($varname) { }
function session_is_registered($varname) { }
class SessionHandler {
  public function __construct() { }
  public function open($save_path, $session_id) { }
  public function close() { }
  public function read($session_id) { }
  public function write($session_id, $session_data) { }
  public function destroy($session_id) { }
  public function gc($maxlifetime) { }
}
