<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function simplexml_load_string() { }
function simplexml_load_file() { }
function libxml_get_errors() { }
function libxml_get_last_error() { }
function libxml_clear_errors() { }
function libxml_use_internal_errors() { }
function libxml_set_streams_context() { }
function libxml_disable_entity_loader() { }
class SimpleXMLElement {
function __construct() { }
function offsetExists() { }
function offsetGet() { }
function offsetSet() { }
function offsetUnset() { }
function getIterator() { }
function count() { }
function xpath() { }
function registerXPathNamespace() { }
function asXML() { }
function getNamespaces() { }
function getDocNamespaces() { }
function children() { }
function getName() { }
function attributes() { }
function addChild() { }
function addAttribute() { }
function __toString() { }
function __get() { }
function __set() { }
function __isset() { }
function __unset() { }
function __destruct() { }
}
class LibXMLError {
function __construct() { }
function __destruct() { }
}
class SimpleXMLElementIterator {
function __construct() { }
function current() { }
function key() { }
function next() { }
function rewind() { }
function valid() { }
function __destruct() { }
}
