<?hh     /* -*- php -*- */
// THIS IS AUTOGENERATED BY builtins_php.ml

define('DEBUG_BACKTRACE_PROVIDE_OBJECT', 0);
define('DEBUG_BACKTRACE_IGNORE_ARGS', 0);
function debug_backtrace($options = 1, $limit = 0) { }
function debug_print_backtrace($options = 0, $limit = 0) { }
function error_get_last() { }
function error_log($message, $message_type = 0, $destination = null, $extra_headers = null) { }
function error_reporting($level = null) { }
function restore_error_handler() { }
function restore_exception_handler() { }
function set_error_handler($error_handler, $error_types = E_ALL) { }
function set_exception_handler($exception_handler) { }
function hphp_set_error_page($page) { }
function hphp_throw_fatal_error($error_msg) { }
function hphp_clear_unflushed() { }
function hphp_debug_caller_info() { }
function trigger_error($error_msg, $error_type = E_USER_NOTICE) { }
function user_error($error_msg, $error_type = E_USER_NOTICE) { }
