<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function hphpd_install_user_command() { }
function hphpd_get_user_commands() { }
function hphpd_break() { }
class DebuggerProxy {
function __construct() { }
function isLocal() { }
function send() { }
function __destruct() { }
}
class DebuggerClient {
const AUTO_COMPLETE_FILENAMES = 0;
const AUTO_COMPLETE_VARIABLES = 0;
const AUTO_COMPLETE_CONSTANTS = 0;
const AUTO_COMPLETE_CLASSES = 0;
const AUTO_COMPLETE_FUNCTIONS = 0;
const AUTO_COMPLETE_CLASS_METHODS = 0;
const AUTO_COMPLETE_CLASS_PROPERTIES = 0;
const AUTO_COMPLETE_CLASS_CONSTANTS = 0;
const AUTO_COMPLETE_KEYWORDS = 0;
const AUTO_COMPLETE_CODE = 0;
function __construct() { }
function quit() { }
function help() { }
function info() { }
function output() { }
function error() { }
function code() { }
function ask() { }
function wrap() { }
function helpTitle() { }
function helpCmds() { }
function helpBody() { }
function helpSection() { }
function tutorial() { }
function getCode() { }
function getCommand() { }
function arg() { }
function argCount() { }
function argValue() { }
function argRest() { }
function args() { }
function send() { }
function xend() { }
function getCurrentLocation() { }
function getStackTrace() { }
function getFrame() { }
function printFrame() { }
function addCompletion() { }
function __destruct() { }
}
