<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
define('SQLITE3_ASSOC', 0);
define('SQLITE3_NUM', 0);
define('SQLITE3_BOTH', 0);
define('SQLITE3_INTEGER', 0);
define('SQLITE3_FLOAT', 0);
define('SQLITE3_TEXT', 0);
define('SQLITE3_BLOB', 0);
define('SQLITE3_NULL', 0);
define('SQLITE3_OPEN_READONLY', 0);
define('SQLITE3_OPEN_READWRITE', 0);
define('SQLITE3_OPEN_CREATE', 0);
class SQLite3 {
function __construct() { }
function open() { }
function close() { }
function exec() { }
function version() { }
function lastinsertrowid() { }
function lasterrorcode() { }
function lasterrormsg() { }
function loadextension() { }
function changes() { }
function escapestring() { }
function prepare() { }
function query() { }
function querysingle() { }
function createfunction() { }
function createaggregate() { }
function openblob() { }
function __destruct() { }
}
class SQLite3Stmt {
function __construct() { }
function paramcount() { }
function close() { }
function reset() { }
function clear() { }
function bindparam() { }
function bindvalue() { }
function execute() { }
function __destruct() { }
}
class SQLite3Result {
function __construct() { }
function numcolumns() { }
function columnname() { }
function columntype() { }
function fetcharray() { }
function reset() { }
function finalize() { }
function __destruct() { }
}
