<?php
// THIS IS AUTOGENERATED BY builtins_php.ml
function bcscale() { }
function bcadd() { }
function bcsub() { }
function bccomp() { }
function bcmul() { }
function bcdiv() { }
function bcmod() { }
function bcpow() { }
function bcpowmod() { }
function bcsqrt() { }
