<?php
/*
 * Purpose: Open a connection to a MySQL Server
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Could not connect: ' . mysql_error());
 *   }
 *   echo 'Connected successfully';
 *   mysql_close($link);
 *   ?>
 * 
 * Output: 
 */
function mysql_connect(String $server = null_string, String $username = null_string, String $password = null_string, Boolean $new_link = false, Int32 $client_flags = 0, Int32 $connect_timeout_ms = -1, Int32 $query_timeout_ms = -1) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Open a persistent connection to a MySQL server
 * Example: 
 * 
 * Output: 
 */
function mysql_pconnect(String $server = null_string, String $username = null_string, String $password = null_string, Int32 $client_flags = 0, Int32 $connect_timeout_ms = -1, Int32 $query_timeout_ms = -1) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Sets the client character set
 * Example: 
 * 
 * Output: 
 */
function mysql_set_charset(String $charset, Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Ping a server connection or reconnect if there is no connection
 * Example:   
 *   <?php
 *   set_time_limit(0);
 *   
 *   $conn = mysql_connect('localhost', 'mysqluser', 'mypass');
 *   $db   = mysql_select_db('mydb');
 *   
 *   /* Assuming this query will take a long time  * / 
 *   $result = mysql_query($sql);
 *   if (!$result) {
 *       echo 'Query #1 failed, exiting.';
 *       exit;
 *   }
 *   
 *   /* Make sure the connection is still alive, if not, try to reconnect  * / 
 *   if (!mysql_ping($conn)) {
 *       echo 'Lost connection, exiting after query #1';
 *       exit;
 *   }
 *   mysql_free_result($result);
 *   
 *   /* So the connection is still alive, let's run another query  * / 
 *   $result2 = mysql_query($sql2);
 *   ?>
 * 
 * Output: 
 */
function mysql_ping(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Escapes a string for use in a mysql_query
 * Example:   
 *   <?php
 *   $item = "Zak's Laptop";
 *   $escaped_item = mysql_escape_string($item);
 *   printf("Escaped string: %s\n", $escaped_item);
 *   ?>
 * 
 * Output:   
 *   Escaped string: Zak\'s Laptop
 */
function mysql_escape_string(String $unescaped_string) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Escapes special characters in a string for use in an SQL statement
 * Example:   
 *   <?php
 *   // Connect
 *   $link = mysql_connect('mysql_host', 'mysql_user', 'mysql_password')
 *       OR die(mysql_error());
 *   
 *   // Query
 *   $query = sprintf("SELECT * FROM users WHERE user='%s' AND password='%s'",
 *               mysql_real_escape_string($user),
 *               mysql_real_escape_string($password));
 *   ?>
 * 
 * Output:   
 *   SELECT * FROM users WHERE user='aidan' AND password='' OR ''=''
 */
function mysql_real_escape_string(String $unescaped_string, Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Returns the name of the character set
 * Example:   
 *   <?php
 *   $link    = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   $charset = mysql_client_encoding($link);
 *   
 *   echo "The current character set is: $charset\n";
 *   ?>
 * 
 * Output:   
 *   The current character set is: latin1
 */
function mysql_client_encoding(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Close MySQL connection
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Could not connect: ' . mysql_error());
 *   }
 *   echo 'Connected successfully';
 *   mysql_close($link);
 *   ?>
 * 
 * Output:   
 *   Connected successfully
 */
function mysql_close(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Returns the numerical value of the error message from previous MySQL operation
 * Example:   
 *   <?php
 *   $link = mysql_connect("localhost", "mysql_user", "mysql_password");
 *   
 *   if (!mysql_select_db("nonexistentdb", $link)) {
 *       echo mysql_errno($link) . ": " . mysql_error($link). "\n";
 *   }
 *   
 *   mysql_select_db("kossu", $link);
 *   if (!mysql_query("SELECT * FROM nonexistenttable", $link)) {
 *       echo mysql_errno($link) . ": " . mysql_error($link) . "\n";
 *   }
 *   ?>
 * 
 * Output:   
 *   1049: Unknown database 'nonexistentdb'
 *   1146: Table 'kossu.nonexistenttable' doesn't exist
 */
function mysql_errno(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Returns the text of the error message from previous MySQL operation
 * Example:   
 *   <?php
 *   $link = mysql_connect("localhost", "mysql_user", "mysql_password");
 *   
 *   mysql_select_db("nonexistentdb", $link);
 *   echo mysql_errno($link) . ": " . mysql_error($link). "\n";
 *   
 *   mysql_select_db("kossu", $link);
 *   mysql_query("SELECT * FROM nonexistenttable", $link);
 *   echo mysql_errno($link) . ": " . mysql_error($link) . "\n";
 *   ?>
 * 
 * Output:   
 *   1049: Unknown database 'nonexistentdb'
 *   1146: Table 'kossu.nonexistenttable' doesn't exist
 */
function mysql_error(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get MySQL client info
 * Example:   
 *   <?php
 *   printf("MySQL client info: %s\n", mysql_get_client_info());
 *   ?>
 * 
 * Output:   
 *   MySQL client info: 3.23.39
 */
function mysql_get_client_info() {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get MySQL host info
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Could not connect: ' . mysql_error());
 *   }
 *   printf("MySQL host info: %s\n", mysql_get_host_info());
 *   ?>
 * 
 * Output:   
 *   MySQL host info: Localhost via UNIX socket
 */
function mysql_get_host_info(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get MySQL protocol info
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Could not connect: ' . mysql_error());
 *   }
 *   printf("MySQL protocol version: %s\n", mysql_get_proto_info());
 *   ?>
 * 
 * Output:   
 *   MySQL protocol version: 10
 */
function mysql_get_proto_info(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get MySQL server info
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Could not connect: ' . mysql_error());
 *   }
 *   printf("MySQL server version: %s\n", mysql_get_server_info());
 *   ?>
 * 
 * Output:   
 *   MySQL server version: 4.0.1-alpha
 */
function mysql_get_server_info(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get information about the most recent query
 * Example:   
 *   INSERT INTO ... SELECT ...
 *   String format: Records: 23 Duplicates: 0 Warnings: 0 
 *   INSERT INTO ... VALUES (...),(...),(...)...
 *   String format: Records: 37 Duplicates: 0 Warnings: 0 
 *   LOAD DATA INFILE ...
 *   String format: Records: 42 Deleted: 0 Skipped: 0 Warnings: 0 
 *   ALTER TABLE
 *   String format: Records: 60 Duplicates: 0 Warnings: 0 
 *   UPDATE
 *   String format: Rows matched: 65 Changed: 65 Warnings: 0
 * 
 * Output: 
 */
function mysql_info(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get the ID generated in the last query
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Could not connect: ' . mysql_error());
 *   }
 *   mysql_select_db('mydb');
 *   
 *   mysql_query("INSERT INTO mytable (product) values ('kossu')");
 *   printf("Last inserted record has id %d\n", mysql_insert_id());
 *   ?>
 * 
 * Output: 
 */
function mysql_insert_id(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get current system status
 * Example:   
 *   <?php
 *   $link   = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   $status = explode('  ', mysql_stat($link));
 *   print_r($status);
 *   ?>
 * 
 * Output:   
 *   Array
 *   (
 *       [0] => Uptime: 5380
 *       [1] => Threads: 2
 *       [2] => Questions: 1321299
 *       [3] => Slow queries: 0
 *       [4] => Opens: 26
 *       [5] => Flush tables: 1
 *       [6] => Open tables: 17
 *       [7] => Queries per second avg: 245.595
 *   )
 */
function mysql_stat(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Return the current thread ID
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   $thread_id = mysql_thread_id($link);
 *   if ($thread_id){
 *       printf("current thread id is %d\n", $thread_id);
 *   }
 *   ?>
 * 
 * Output:   
 *   current thread id is 73
 */
function mysql_thread_id(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Create a MySQL database
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Could not connect: ' . mysql_error());
 *   }
 *   
 *   $sql = 'CREATE DATABASE my_db';
 *   if (mysql_query($sql, $link)) {
 *       echo "Database my_db created successfully\n";
 *   } else {
 *       echo 'Error creating database: ' . mysql_error() . "\n";
 *   }
 *   ?>
 * 
 * Output:   
 *   Database my_db created successfully
 */
function mysql_create_db(String $db, Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Select a MySQL database
 * Example:   
 *   <?php
 *   
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Not connected : ' . mysql_error());
 *   }
 *   
 *   // make foo the current db
 *   $db_selected = mysql_select_db('foo', $link);
 *   if (!$db_selected) {
 *       die ('Can\'t use foo : ' . mysql_error());
 *   }
 *   ?>
 * 
 * Output: 
 */
function mysql_select_db(String $db, Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Drop (delete) a MySQL database
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Could not connect: ' . mysql_error());
 *   }
 *   
 *   $sql = 'DROP DATABASE my_db';
 *   if (mysql_query($sql, $link)) {
 *       echo "Database my_db was successfully dropped\n";
 *   } else {
 *       echo 'Error dropping database: ' . mysql_error() . "\n";
 *   }
 *   ?>
 * 
 * Output: 
 */
function mysql_drop_db(String $db, Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get number of affected rows in previous MySQL operation
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Could not connect: ' . mysql_error());
 *   }
 *   mysql_select_db('mydb');
 *   
 *   /* this should return the correct numbers of deleted records  * / 
 *   mysql_query('DELETE FROM mytable WHERE id < 10');
 *   printf("Records deleted: %d\n", mysql_affected_rows());
 *   
 *   /* with a where clause that is never true, it should return 0  * / 
 *   mysql_query('DELETE FROM mytable WHERE 0');
 *   printf("Records deleted: %d\n", mysql_affected_rows());
 *   ?>
 * 
 * Output:   
 *   Records deleted: 10
 *   Records deleted: 0
 */
function mysql_affected_rows(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

function mysql_set_timeout(Int32 $query_timeout_ms = -1, Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Send a MySQL query
 * Example:   
 *   <?php
 *   $result = mysql_query('SELECT * WHERE 1=1');
 *   if (!$result) {
 *       die('Invalid query: ' . mysql_error());
 *   }
 *   
 *   ?>
 * 
 * Output: 
 */
function mysql_query(String $query, Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Send an SQL query to MySQL without fetching and buffering the result rows.
 * Example: 
 * 
 * Output: 
 */
function mysql_unbuffered_query(String $query, Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Send a MySQL query
 * Example:   
 *   <?php
 *   
 *   if (!$link = mysql_connect('mysql_host', 'mysql_user', 'mysql_password')) {
 *       echo 'Could not connect to mysql';
 *       exit;
 *   }
 *   
 *   if (!mysql_select_db('mysql_dbname', $link)) {
 *       echo 'Could not select database';
 *       exit;
 *   }
 *   
 *   $sql    = 'SELECT foo FROM bar WHERE id = 42';
 *   $result = mysql_query($sql, $link);
 *   
 *   if (!$result) {
 *       echo "DB Error, could not query the database\n";
 *       echo 'MySQL Error: ' . mysql_error();
 *       exit;
 *   }
 *   
 *   while ($row = mysql_fetch_assoc($result)) {
 *       echo $row['foo'];
 *   }
 *   
 *   mysql_free_result($result);
 *   
 *   ?>
 * 
 * Output: 
 */
function mysql_db_query(String $database, String $query, Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: List databases available on a MySQL server
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   $db_list = mysql_list_dbs($link);
 *   
 *   while ($row = mysql_fetch_object($db_list)) {
 *        echo $row->Database . "\n";
 *   }
 *   ?>
 * 
 * Output:   
 *   database1
 *   database2
 *   database3
 */
function mysql_list_dbs(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: List tables in a MySQL database
 * Example:   
 *   <?php
 *   $dbname = 'mysql_dbname';
 *   
 *   if (!mysql_connect('mysql_host', 'mysql_user', 'mysql_password')) {
 *       echo 'Could not connect to mysql';
 *       exit;
 *   }
 *   
 *   $sql = "SHOW TABLES FROM $dbname";
 *   $result = mysql_query($sql);
 *   
 *   if (!$result) {
 *       echo "DB Error, could not list tables\n";
 *       echo 'MySQL Error: ' . mysql_error();
 *       exit;
 *   }
 *   
 *   while ($row = mysql_fetch_row($result)) {
 *       echo "Table: {$row[0]}\n";
 *   }
 *   
 *   mysql_free_result($result);
 *   ?>
 * 
 * Output: 
 */
function mysql_list_tables(String $database, Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: List MySQL table fields
 * Example:   
 *   <?php
 *   $result = mysql_query("SHOW COLUMNS FROM sometable");
 *   if (!$result) {
 *       echo 'Could not run query: ' . mysql_error();
 *       exit;
 *   }
 *   if (mysql_num_rows($result) > 0) {
 *       while ($row = mysql_fetch_assoc($result)) {
 *           print_r($row);
 *       }
 *   }
 *   ?>
 * 
 * Output:   
 *   Array
 *   (
 *       [Field] => id
 *       [Type] => int(7)
 *       [Null] =>  
 *       [Key] => PRI
 *       [Default] =>
 *       [Extra] => auto_increment
 *   )
 *   Array
 *   (
 *       [Field] => email
 *       [Type] => varchar(100)
 *       [Null] =>
 *       [Key] =>
 *       [Default] =>
 *       [Extra] =>
 *   )
 */
function mysql_list_fields(String $database_name, String $table_name, Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: List MySQL processes
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   
 *   $result = mysql_list_processes($link);
 *   while ($row = mysql_fetch_assoc($result)){
 *       printf("%s %s %s %s %s\n", $row["Id"], $row["Host"], $row["db"],
 *           $row["Command"], $row["Time"]);
 *   }
 *   mysql_free_result($result);
 *   ?>
 * 
 * Output:   
 *   1 localhost test Processlist 0
 *   4 localhost mysql sleep 5
 */
function mysql_list_processes(Variant $link_identifier = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get result data
 * Example:   
 *   <?php
 *   error_reporting(E_ALL);
 *   
 *   $link = mysql_connect('dbhost', 'username', 'password');
 *   $db_list = mysql_list_dbs($link);
 *   
 *   $i = 0;
 *   $cnt = mysql_num_rows($db_list);
 *   while ($i < $cnt) {
 *       echo mysql_db_name($db_list, $i) . "\n";
 *       $i++;
 *   }
 *   ?>
 * 
 * Output: 
 */
function mysql_db_name(Variant $result, Int32 $row, Variant $field = null_variant) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get table name of field
 * Example:   
 *   <?php
 *   mysql_connect("localhost", "mysql_user", "mysql_password");
 *   $result = mysql_list_tables("mydb");
 *   $num_rows = mysql_num_rows($result);
 *   for ($i = 0; $i < $num_rows; $i++) {
 *       echo "Table: ", mysql_tablename($result, $i), "\n";
 *   }
 *   
 *   mysql_free_result($result);
 *   ?>
 * 
 * Output: 
 */
function mysql_tablename(Variant $result, Int32 $i) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get number of fields in result
 * Example:   
 *   <?php
 *   $result = mysql_query("SELECT id,email FROM people WHERE id = '42'");
 *   if (!$result) {
 *       echo 'Could not run query: ' . mysql_error();
 *       exit;
 *   }
 *   
 *   /* returns 2 because id,email === two fields  * / 
 *   echo mysql_num_fields($result);
 *   ?>
 * 
 * Output: 
 */
function mysql_num_fields(Variant $result) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get number of rows in result
 * Example:   
 *   <?php
 *   
 *   $link = mysql_connect("localhost", "mysql_user", "mysql_password");
 *   mysql_select_db("database", $link);
 *   
 *   $result = mysql_query("SELECT * FROM table1", $link);
 *   $num_rows = mysql_num_rows($result);
 *   
 *   echo "$num_rows Rows\n";
 *   
 *   ?>
 * 
 * Output: 
 */
function mysql_num_rows(Variant $result) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Free result memory
 * Example:   
 *   <?php
 *   $result = mysql_query("SELECT id,email FROM people WHERE id = '42'");
 *   if (!$result) {
 *       echo 'Could not run query: ' . mysql_error();
 *       exit;
 *   }
 *   /* Use the result, assuming we're done with it afterwards  * / 
 *   $row = mysql_fetch_assoc($result);
 *   
 *   /* Now we free up the result and continue on with our script  * / 
 *   mysql_free_result($result);
 *   
 *   echo $row['id'];
 *   echo $row['email'];
 *   ?>
 * 
 * Output: 
 */
function mysql_free_result(Variant $result) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Move internal result pointer
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Could not connect: ' . mysql_error());
 *   }
 *   $db_selected = mysql_select_db('sample_db');
 *   if (!$db_selected) {
 *       die('Could not select database: ' . mysql_error());
 *   }
 *   $query = 'SELECT last_name, first_name FROM friends';
 *   $result = mysql_query($query);
 *   if (!$result) {
 *       die('Query failed: ' . mysql_error());
 *   }
 *   /* fetch rows in reverse order  * / 
 *   for ($i = mysql_num_rows($result) - 1; $i >= 0; $i--) {
 *       if (!mysql_data_seek($result, $i)) {
 *           echo "Cannot seek to row $i: " . mysql_error() . "\n";
 *           continue;
 *       }
 *   
 *       if (!($row = mysql_fetch_assoc($result))) {
 *           continue;
 *       }
 *   
 *       echo $row['last_name'] . ' ' . $row['first_name'] . "<br />\n";
 *   }
 *   
 *   mysql_free_result($result);
 *   ?>
 * 
 * Output: 
 */
function mysql_data_seek(Variant $result, Int32 $row) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get a result row as an enumerated array
 * Example:   
 *   <?php
 *   $result = mysql_query("SELECT id,email FROM people WHERE id = '42'");
 *   if (!$result) {
 *       echo 'Could not run query: ' . mysql_error();
 *       exit;
 *   }
 *   $row = mysql_fetch_row($result);
 *   
 *   echo $row[0]; // 42
 *   echo $row[1]; // the email value
 *   ?>
 * 
 * Output: 
 */
function mysql_fetch_row(Variant $result) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Fetch a result row as an associative array
 * Example:   
 *   <?php
 *   
 *   $conn = mysql_connect("localhost", "mysql_user", "mysql_password");
 *   
 *   if (!$conn) {
 *       echo "Unable to connect to DB: " . mysql_error();
 *       exit;
 *   }
 *     
 *   if (!mysql_select_db("mydbname")) {
 *       echo "Unable to select mydbname: " . mysql_error();
 *       exit;
 *   }
 *   
 *   $sql = "SELECT id as userid, fullname, userstatus 
 *           FROM   sometable
 *           WHERE  userstatus = 1";
 *   
 *   $result = mysql_query($sql);
 *   
 *   if (!$result) {
 *       echo "Could not successfully run query ($sql) from DB: " . mysql_error();
 *       exit;
 *   }
 *   
 *   if (mysql_num_rows($result) == 0) {
 *       echo "No rows found, nothing to print so am exiting";
 *       exit;
 *   }
 *   
 *   // While a row of data exists, put that row in $row as an associative array
 *   // Note: If you're expecting just one row, no need to use a loop
 *   // Note: If you put extract($row); inside the following loop, you'll
 *   //       then create $userid, $fullname, and $userstatus
 *   while ($row = mysql_fetch_assoc($result)) {
 *       echo $row["userid"];
 *       echo $row["fullname"];
 *       echo $row["userstatus"];
 *   }
 *   
 *   mysql_free_result($result);
 *   
 *   ?>
 * 
 * Output: 
 */
function mysql_fetch_assoc(Variant $result) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Fetch a result row as an associative array, a numeric array, or both
 * Example:   
 *   SELECT table1.field AS foo, table2.field AS bar FROM table1, table2
 * 
 * Output: 
 */
function mysql_fetch_array(Variant $result, Int32 $result_type = 3) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get the length of each output in a result
 * Example:   
 *   <?php
 *   $result = mysql_query("SELECT id,email FROM people WHERE id = '42'");
 *   if (!$result) {
 *       echo 'Could not run query: ' . mysql_error();
 *       exit;
 *   }
 *   $row     = mysql_fetch_assoc($result);
 *   $lengths = mysql_fetch_lengths($result);
 *   
 *   print_r($row);
 *   print_r($lengths);
 *   ?>
 * 
 * Output:   
 *   Array
 *   (
 *       [id] => 42
 *       [email] => user@example.com
 *   )
 *   Array
 *   (
 *       [0] => 2
 *       [1] => 16
 *   )
 */
function mysql_fetch_lengths(Variant $result) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Fetch a result row as an object
 * Example:   
 *   <?php
 *   mysql_connect("hostname", "user", "password");
 *   mysql_select_db("mydb");
 *   $result = mysql_query("select * from mytable");
 *   while ($row = mysql_fetch_object($result)) {
 *       echo $row->user_id;
 *       echo $row->fullname;
 *   }
 *   mysql_free_result($result);
 *   ?>
 * 
 * Output: 
 */
function mysql_fetch_object(Variant $result, String $class_name = "stdClass", VariantVec $params = null) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get result data
 * Example:   
 *   <?php
 *   $link = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Could not connect: ' . mysql_error());
 *   }
 *   if (!mysql_select_db('database_name')) {
 *       die('Could not select database: ' . mysql_error());
 *   }
 *   $result = mysql_query('SELECT name FROM work.employee');
 *   if (!$result) {
 *       die('Could not query:' . mysql_error());
 *   }
 *   echo mysql_result($result, 2); // outputs third employee's name
 *   
 *   mysql_close($link);
 *   ?>
 * 
 * Output: 
 */
function mysql_result(Variant $result, Int32 $row, Variant $field = null_variant) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get column information from a result and return as an object
 * Example:   
 *   <?php
 *   $conn = mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$conn) {
 *       die('Could not connect: ' . mysql_error());
 *   }
 *   mysql_select_db('database');
 *   $result = mysql_query('select * from table');
 *   if (!$result) {
 *       die('Query failed: ' . mysql_error());
 *   }
 *   /* get column metadata  * / 
 *   $i = 0;
 *   while ($i < mysql_num_fields($result)) {
 *       echo "Information for column $i:<br />\n";
 *       $meta = mysql_fetch_field($result, $i);
 *       if (!$meta) {
 *           echo "No information available<br />\n";
 *       }
 *       echo "<pre>
 *   blob:         $meta->blob
 *   max_length:   $meta->max_length
 *   multiple_key: $meta->multiple_key
 *   name:         $meta->name
 *   not_null:     $meta->not_null
 *   numeric:      $meta->numeric
 *   primary_key:  $meta->primary_key
 *   table:        $meta->table
 *   type:         $meta->type
 *   unique_key:   $meta->unique_key
 *   unsigned:     $meta->unsigned
 *   zerofill:     $meta->zerofill
 *   </pre>";
 *       $i++;
 *   }
 *   mysql_free_result($result);
 *   ?>
 * 
 * Output: 
 */
function mysql_fetch_field(Variant $result, Int32 $field = -1) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Set result pointer to a specified field offset
 * Example: 
 * 
 * Output: 
 */
function mysql_field_seek(Variant $result, Int32 $field = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get the name of the specified field in a result
 * Example:   
 *   <?php
 *   /* The users table consists of three fields:
 *   *   user_id
 *   *   username
 *   *   password.
 *    * / 
 *   $link = @mysql_connect('localhost', 'mysql_user', 'mysql_password');
 *   if (!$link) {
 *       die('Could not connect to MySQL server: ' . mysql_error());
 *   }
 *   $dbname = 'mydb';
 *   $db_selected = mysql_select_db($dbname, $link);
 *   if (!$db_selected) {
 *       die("Could not set $dbname: " . mysql_error());
 *   }
 *   $res = mysql_query('select * from users', $link);
 *   
 *   echo mysql_field_name($res, 0) . "\n";
 *   echo mysql_field_name($res, 2);
 *   ?>
 * 
 * Output:   
 *   user_id
 *   password
 */
function mysql_field_name(Variant $result, Int32 $field = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get name of the table the specified field is in
 * Example:   
 *   <?php
 *   
 *   $query = "SELECT account.*, country.* FROM account, country WHERE country.name = 'Portugal' AND account.country_id = country.id";
 *   
 *   // get the result from the DB
 *   $result = mysql_query($query);
 *   
 *   // Lists the table name and then the field name
 *   for ($i = 0; $i < mysql_num_fields($result); ++$i) {
 *       $table = mysql_field_table($result, $i);
 *       $field = mysql_field_name($result, $i);
 *   
 *       echo  "$table: $field\n";
 *   }
 *   
 *   ?>
 * 
 * Output: 
 */
function mysql_field_table(Variant $result, Int32 $field = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Returns the length of the specified field
 * Example:   
 *   <?php
 *   $result = mysql_query("SELECT id,email FROM people WHERE id = '42'");
 *   if (!$result) {
 *       echo 'Could not run query: ' . mysql_error();
 *       exit;
 *   }
 *   
 *   // Will get the length of the id field as specified in the database
 *   // schema. 
 *   $length = mysql_field_len($result, 0);
 *   echo $length;
 *   ?>
 * 
 * Output: 
 */
function mysql_field_len(Variant $result, Int32 $field = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get the type of the specified field in a result
 * Example:   
 *   <?php
 *   mysql_connect("localhost", "mysql_username", "mysql_password");
 *   mysql_select_db("mysql");
 *   $result = mysql_query("SELECT * FROM func");
 *   $fields = mysql_num_fields($result);
 *   $rows   = mysql_num_rows($result);
 *   $table  = mysql_field_table($result, 0);
 *   echo "Your '" . $table . "' table has " . $fields . " fields and " . $rows . " record(s)\n";
 *   echo "The table has the following fields:\n";
 *   for ($i=0; $i < $fields; $i++) {
 *       $type  = mysql_field_type($result, $i);
 *       $name  = mysql_field_name($result, $i);
 *       $len   = mysql_field_len($result, $i);
 *       $flags = mysql_field_flags($result, $i);
 *       echo $type . " " . $name . " " . $len . " " . $flags . "\n";
 *   }
 *   mysql_free_result($result);
 *   mysql_close();
 *   ?>
 * 
 * Output:   
 *   Your 'func' table has 4 fields and 1 record(s)
 *   The table has the following fields:
 *   string name 64 not_null primary_key binary
 *   int ret 1 not_null
 *   string dl 128 not_null
 *   string type 9 not_null enum
 */
function mysql_field_type(Variant $result, Int32 $field = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

/*
 * Purpose: Get the flags associated with the specified field in a result
 * Example:   
 *   <?php
 *   $result = mysql_query("SELECT id,email FROM people WHERE id = '42'");
 *   if (!$result) {
 *       echo 'Could not run query: ' . mysql_error();
 *       exit;
 *   }
 *   $flags = mysql_field_flags($result, 0);
 *   
 *   echo $flags;
 *   print_r(explode(' ', $flags));
 *   ?>
 * 
 * Output:   
 *   not_null primary_key auto_increment
 *   Array
 *   (
 *       [0] => not_null
 *       [1] => primary_key
 *       [2] => auto_increment
 *   )
 */
function mysql_field_flags(Variant $result, Int32 $field = 0) {
 // THIS IS AUTOGENERATED BY builtins_php.ml
  
}

